steps:
# Paso 1: Instalar Firebase CLI
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-g', 'firebase-tools@latest']
  id: 'install-firebase'

# Paso 2: Desplegar solo hosting
- name: 'gcr.io/firebase/hosting'
  args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']
  timeout: 600s
  id: 'deploy-hosting'
options:
  machineType: 'E2_HIGHCPU_8'
