steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-g', 'firebase-tools@latest']
  id: 'install-firebase'

- name: 'gcr.io/firebase/hosting'
  args: ['deploy', '--project=$PROJECT_ID', '--only=hosting', '--token=$_FIREBASE_TOKEN']
  secretEnv: ['_FIREBASE_TOKEN']
  timeout: 600s
  id: 'deploy-hosting'
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/klosetshop-d3064/secrets/firebase-token/versions/latest
    env: '_FIREBASE_TOKEN'
