steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-g', 'firebase-tools']
  id: 'install-firebase'

- name: 'gcr.io/firebase/hosting'
  args: ['deploy', '--project=klosetshop-d3064', '--only=hosting']
  timeout: 600s
  id: 'deploy-hosting'
options:
  machineType: 'E2_HIGHCPU_8'
